# -*- coding: utf-8 -*-
"""data_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ckBug9892fprbFSgshFfZJqMOBji6eaX
"""

import zipfile

def extract_data(zip_file_path, extract_to):
    """
    Extracts the FMA dataset from a zip file to a specified directory.

    Parameters:
        zip_file_path (str): Path to the FMA dataset zip file.
        extract_to (str): Directory where the dataset will be extracted.
    """
    # Extract the zip file
    with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
        zip_ref.extractall(extract_to)

    print("Dataset extraction complete.")

def main():
    # Path to the FMA dataset zip file
    zip_file_path = 'fma_large.zip'

    # Directory to extract the dataset to
    extract_to = 'fma_dataset'

    # Extract the dataset
    extract_data(zip_file_path, extract_to)

if __name__ == "__main__":
    main()