# -*- coding: utf-8 -*-
"""views_flask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ckBug9892fprbFSgshFfZJqMOBji6eaX
"""

from flask import Flask, render_template, request

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/recommendations')
def recommendations():
    recommendations = ['Track 1', 'Track 2', 'Track 3']  # Example recommendations
    return render_template('recommendations.html', recommendations=recommendations)

@app.route('/submit_feedback', methods=['POST'])
def submit_feedback():
    feedback = request.form['feedback']
    # Process feedback
    return 'Feedback submitted successfully!'

if __name__ == '__main__':
    app.run(debug=True)