# -*- coding: utf-8 -*-
"""web_application.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ckBug9892fprbFSgshFfZJqMOBji6eaX
"""

from flask import Flask, render_template, request
from kafka import KafkaProducer, KafkaConsumer
import json

app = Flask(__name__)

# Initialize Kafka producer and consumer
producer = KafkaProducer(bootstrap_servers='localhost:9092', value_serializer=lambda v: json.dumps(v).encode('utf-8'))
consumer = KafkaConsumer('recommendations', bootstrap_servers='localhost:9092', auto_offset_reset='latest', group_id=None)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/recommendations')
def recommendations():
    # Fetch recommendations from Kafka consumer
    recommended_tracks = []
    for message in consumer:
        recommendation = json.loads(message.value)
        recommended_tracks.append(recommendation)
        if len(recommended_tracks) >= 10:  # Limit recommendations to 10 tracks
            break

    return render_template('recommendations.html', recommendations=recommended_tracks)

@app.route('/submit_feedback', methods=['POST'])
def submit_feedback():
    feedback = request.form['feedback']

    # Process feedback and update recommendation model if needed

    return 'Feedback submitted successfully!'

if __name__ == '__main__':
    app.run(debug=True)